### ISSUE TITLE
Potential crates.io release

### ISSUE THREAD

**Issue by leoschwarz** [zeyla/iso15924.rs#1]
Hi, I was wondering if you would like to publish this crate to `crates.io` as a 0.1.0 version or if there are things you would like to get done before that? Maybe the runtime allocations could be replaced with const declarations?

As for semver versioning, I think updating the data when it adds new scripts is not a breaking change (removing them I'd consider one since it could break existing code) but it probably should be a minor version bump and there should be a crate level method to query the revision of the data at any time.

**Comment by zeyla** [comment]
Sorry for the (really) late reply. I'm going to work on fixing up this lib this week and then I'll release a 0.1.0. I'll take a look at your PR too, #2.

**Comment by zeyla** [comment]
Hi, I've rewritten the library to not be bad. If you're still interested in this (I'd understand if you're not) and have time in the next week, any feedback would be appreciated. Otherwise I'll 0.1.0 it. Thanks

**Comment by leoschwarz** [comment]
Hey thanks for your efforts! I almost forgot to reply. I'm currently not working on my project which uses this (I think it was the musicbrainz crate). 

I haven't had a thorough look at the API and differences to before, but from looking at the code it really looks well implemented now and I think having the parser available too is a good solution to the versioning problem. I don't think there's any reason to wait with a 0.1.0.

**Comment by zeyla** [comment]
Thanks, I've published it: https://crates.io/crates/iso15924
